### ISSUE TITLE
Request for improvements

### ISSUE THREAD

**Issue by amanxng** [burgerga/shinyTime#4] opened 2016-09-29 03:30 UTC
@burgerga Thanks for this handy time control for Shiny. I have a few improvement requests...
1. It is presently possible for someone to enter h > 23 and m > 59 (same for seconds I guess). It will be good if incorrect values such as these get reset to 00 on tab-out. Or else block direct typing... that may become a pain for minutes and seconds though.
2. Aesthetics: if you put a Shiny date control and (this) Shiny time control side by side, it is as if they don't sit well together. Here are a few humble suggestions:
- Instead of [00 |]:[00 |]:[00 |] try and achieve: [ 00|]h : [ 00|]m : [ 00|]s
  - Interchange space around the digits, 
  - Replace ":" with "h : " and "m : ", 
  - Use "s" to denote seconds
- Use the same CSS classes as used by Shiny's date control: 
  - form-control (should be quite safe, I tried inserting it for both hour and minute boxes via inspect-element, result looks good - rounded rectangles and all, but I can not use the control now... spinners dont work), 
  - datepicker (not sure of unwanted side effects)
  - shinyjs-resettable (not sure what this means)

I will be happy to test out your changes or any other improvements you make to shinyTime.

**Comment by burgerga** [comment] 2016-09-29 18:58
@amanxng Thanks for your kind words and suggestions, it's nice to get some feedback! I'm currently abroad so when I am home again I'll reply to you in more detail (already tried some of your suggestions previously, but at that time it was not a priority to get them done).

**Comment by burgerga** [comment] 2016-09-30 15:16
So I'm at a place with Wifi with some time to kill, so let's have a look ;)
1. Yes, I agree, however, this is a problem with numeric inputs in shiny in general: https://github.com/rstudio/shiny/issues/927 (doesn't seem a priority to them)
   For shinyTime it would be nice to have though, especially since the values are used to create DateTime classes. I'll check if this is something that can easily be done in javascript.
2. It's quite ugly indeed. I made some quick changes (removed the `:`s, and added class `form-control`, and increased the width to get some room for the spinners) in https://github.com/burgerga/shinyTime/commit/f6ae6325d1822815f89911b89c92bf41e02dd101 and it now looks like this:
   ![image](https://cloud.githubusercontent.com/assets/907362/18996368/60788372-8730-11e6-8ff8-c2a9a9dd67c4.png)  
   The reason it's so wide is because there needs to be some room for the spinners, and the problem is that you can't specify that it should be as wide as 2 characters, so to set the width, it's guessing and hoping that it works out for all different fonts and font sizes :(  
   I used to have H M S next to the inputs, but didn't really like them, but if you want to give it a go, it's really easy to change the appearance of the input by changing https://github.com/burgerga/shinyTime/blob/master/R/input-time.R#L52-L72
   Maybe if you can make it look good, I'll consider it again ;)

Let me know what you think!

**Comment by amanxng** [comment] 2016-10-01 04:25
Thanks @burgerga. In which branch have you made these changes? feat/gh4? I guess I can use devtools to install the latest code.

**Comment by burgerga** [comment] 2016-10-01 05:01
Yes that's the one

**Comment by amanxng** [comment] 2016-10-04 07:24
Definitely looks better... however it can be a little less wide... but like you said, it is guessing the size.

<img width="311" alt="screen shot 2016-10-04 at 12 44 12 pm" src="https://cloud.githubusercontent.com/assets/15208304/19065295/621ed39a-8a30-11e6-9b92-67c7d6342af5.png">

The only way "h", "m" and "s" will look good will be if they are a part of the background "image" in the control and occupy the space between the numbers and the spinners. Any other way will break the "smoothness / visual continuity" of the control.

When you get the time it will be great if you can build the tab-out validation... will save me from doing this validation in my code (on submit / action) :-). And enhance usability.

**Comment by burgerga** [comment] 2016-10-04 07:42
Yes, I completely agree. 
What browser are you using? Safari? Because in my browser there isn't any space between the numbers and the spinners (in Chrome the padding is on the right of the spinners, which doesn't seem to be the case in yours (and in Firefox the spinners don't seem to end up in the input element at all)) 
Ugh, browser dependent stuff :-1: 

So conclusion, it's not perfect but better than what we have so far? I will look for a solution where I don't need to guess the width, but in the meantime I can probably already merge this. 

EDIT: Oh yes, your last point, yes I will! I'm thinking clamping instead of zeroing, so for example for the hours <0 goes to 0, and >23 to 23.

**Comment by amanxng** [comment] 2016-10-04 07:50
You are right! My snapshot was from R Studio's "Run in Window". I have since checked it in Firefox and Chrome - very different behavior. Since this is definitely better than before, it is a good idea to merge this.

**Comment by burgerga** [comment] 2016-10-04 17:45
I have added the validation, let me know what you think..

**Comment by amanxng** [comment] 2016-10-05 09:00
Tested this... Couple of inputs:
1. Instead of changing any number > valid to largestValid (23 or 59), it will be better to change them to 00. Any non-number is already getting this treatment, eg "ab" gets changed to 00.
2. Just found out that it is possible to enter decimals. This should also get the same treatment as 1. above.

**Comment by burgerga** [comment] 2016-10-05 09:40
Ok will do, it might indeed be best to treat all non-valid inputs in the same way.
And decimals, sigh... Nice find, I will fix those as well.

PS I was thinking about why `.` is allowed in a numeric input with step size 1, but how else will you input 13 as 1.3e1 :P

**Comment by burgerga** [comment] 2016-10-05 10:09
Updated the input validation:
- Scientific notation is rewritten to fixed, eg, 0.1e1 becomes 1
- Out-of-range becomes 0 (also makes more sense for 24 to go 0 instead of 23)
- Decimals go to 0 (I first test if it's integer, so 13.0 is still 13, and 0.1e1 is still 1)

**Comment by amanxng** [comment] 2016-10-07 02:49
Awesome mate! Let me check this out.

In about a week's time the application I am working on (which uses ShinyTime) will be released to wider (but internal) audience... that will give you / us more testing hands ;-)

**Comment by burgerga** [comment] 2016-10-07 11:33
Merged to master and submitted to CRAN as version 0.2.1

**Closed as completed by burgerga** 2016-10-07 11:33 UTC
Labels: enhancement
