### ISSUE TITLE
12 hour format option?

### ISSUE THREAD

**Issue by BajczA475** [burgerga/shinyTime#17] opened 2022-07-13 18:29 UTC
Hi, cool app! I was wondering if you could add a format argument, like that in dateInput, that allows for toggling between 24 hour and 12 hour time formats? My end users will be less familiar with 24-hour format, but that seems to be the only option at present. Thanks!

A
--

**Comment by burgerga** [comment] 2022-07-20 20:06
Sorry for the late reply, my notification settings were all wrong. I will close this as a duplicate of #12, and we can continue discussing it there :)

**Closed as not planned by burgerga** 2022-07-20 20:06 UTC
Labels: duplicate
